name: drug-search-wf
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    name: Build and Push Docker image to Azure Registry 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.SANDBOX_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: flasitcr.azurecr.io
        username: ${{ secrets.SANDBOX_REGISTRY_USERNAME }}
        password: ${{ secrets.SANDBOX_REGISTRY_PASSWORD }}
    - run: |
        docker build -t flasitcr/action-drug-search-tailwind:latest . 
        docker push flasitcr/action-drug-search-tailwind:latest

  # docker:
  #   name: Build and Push Docker image to Docker Hub
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     -
  #       name: Login to DockerHub
  #       uses: docker/login-action@v1 
  #       with:
  #         username: ${{ secrets.DOCKER_NAME }}
  #         password: ${{ secrets.DOCKER_SECRET }}
  #     -
  #       name: Build and push
  #       id: docker_build
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         tags: weifang993/action-drug-search-tailwind:latest
  #     -
  #       name: Image digest
  #       run: echo ${{ steps.docker_build.outputs.digest }}