name: drug-search-wf
on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_SECRET }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: weifang993/action-drug-search-tailwind:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}